### ISSUE TITLE
Linking WG org from datatracker

### ISSUE THREAD

**Issue by martinthomson** [ietf-gitwg/draft-ietf-git-github-wg-configuration#2]
This needs to be more concrete than the current text.

I just removed the following from -using:

> A simple example of how to do this is to include a link to the GitHub
organization on the WG Charter page in the datatracker under More Info.
Similarly, if there are multiple mailing list options, links to those mailing
lists should be given.  An example of this is at
https://datatracker.ietf.org/wg/quic/charter/.

I wouldn't recommend that exact language, but the the text definitely should mandate some means of linking from working group status pages to the GitHub organization.

**Comment by paulehoffman** [comment]
Sorry to be late on this. I don't see what more concrete thing you are asking for. The current text already has the steps, including putting a pointer on the WG page (although not in the charter itself).

**Comment by richsalz** [comment]
There is work-in-progress to add "general external references" to each of users, groups, docs, in datatracker.  Some details are in https://mailarchive.ietf.org/arch/msg/tools-discuss/WcM3k0GUQHYvuVTuHV1145fPVWM

**Comment by chris-wood** [comment]
Discussed in Singapore; will add some text in this document.
