### ISSUE TITLE
Document header containing important links

### ISSUE THREAD

**Issue by martinthomson** [ietf-gitwg/draft-ietf-git-github-wg-configuration#5]
From @mnot in ietf-gitwg/using-github#9:

> In the git-using WG's I've participated in, it's been proven useful to add a note at the top of drafts in development that link to the draft's repo, issues list, and datatracker status page.
>
> This makes it easier for readers to find important resources.

(I tried transferring this issue, but was not successful.  Yay for new GitHub features.)

**Comment by paulehoffman** [comment]
This feels like it should be in draft-ietf-git-using-github, not in draft-ietf-git-github-wg-configuration. I don't see a way to configure  this automatically that would be at all reliable.

**Comment by chris-wood** [comment]
Discussed in Singapore; closing.
