### ISSUE TITLE
Suggest that repositories include links to rendered and rfcdiff versions

### ISSUE THREAD

**Issue by chris-wood** [ietf-gitwg/draft-ietf-git-github-wg-configuration#6]
This is helpful for people looking to read diffs between an editor's copy and an I-D copy in data tracker. Fortunately, Martin's tooling sets this up automatically! Perhaps we just need to add a comment here that this should be done. @paulehoffman, what do you think?

**Comment by paulehoffman** [comment]
This feels like it should be in draft-ietf-git-using-github, not in draft-ietf-git-github-wg-configuration. It would be a useful feature, but I don't see how it could be automated.

**Comment by chris-wood** [comment]
Discussed in Singapore; closing.
